apiVersion: v1
kind: Secret
metadata:
  name: openai-microservices-secret
type: Opaque
data:
  openai-api-key: c2stNXZpNkw3SW5QSFBWTUN6RW10U0VUM0JsYmtGSlFwR05peU1vU2s1T1I5RFdtMlVX
  database_host: ZGF0YWJhc2UtMS5jMWhmbG9mYnplenouZXUtd2VzdC0yLnJkcy5hbWF6b25hd3MuY29t
  database_port: MzMwNg==
  database_user: YWRtaW4=
  database_pwd: Tkg4amRFRzZtRVd0ZkpKWks5d0w=
  database: Y2hhdF9zZXJ2aWNlX2RiX2Rldg==
  api-key: YSY5WDVSNF53c3lqS2YyOEdoUHh6I04jdjZDJExAIQ==

