name: Build and Push Docker Images

on:
  push:
    branches:
      - develop
      - stage
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Extract branch name
      id: extract_branch
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

    - name: Build and push chat_service image
      uses: docker/build-push-action@v2
      with:
        context: ./chat_service
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/chat_service:${{ steps.extract_branch.outputs.branch }}-latest

    - name: Build and push edit_service image
      uses: docker/build-push-action@v2
      with:
        context: ./edit_service
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/edit_service:${{ steps.extract_branch.outputs.branch }}-latest

    - name: Build and push completions_service image
      uses: docker/build-push-action@v2
      with:
        context: ./completions_service
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/completions_service:${{ steps.extract_branch.outputs.branch }}-latest

    - name: Build and push image_service image
      uses: docker/build-push-action@v2
      with:
        context: ./image_service
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/image_service:${{ steps.extract_branch.outputs.branch }}-latest

    - name: Install additional Python packages
      run: pip install PyYAML

    - name: Run tests
      uses: docker://python:3.10
      with:
        entrypoint: /bin/sh
        args: -c "pip install pytest && pytest ./tests"