name: completions-service build and push

on:
  push:
    branches:
      - develop
      - stage
      - main
  pull_request:
    branches:
      - develop
      - stage
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Extract branch name
      id: extract_branch
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

    - name: Build and push completions_service image
      uses: docker/build-push-action@v2
      with:
        context: ./completions_service
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/completions_service:${{ steps.extract_branch.outputs.branch }}-latest